export const ALL = [
  'AIIMS 4 (Full)',
  'Air Observer',
  'Assessor',
  'Assessor - TAE',
  'Aviation Radio Operator',
  'Beacon User',
  'Bush Fire Awareness',
  'Cadet Program',
  'Cadet Trainer Endorsement Workshop',
  'Certificate II in Public Safety (SES Ops)',
  'Certificate II in Public Safety (SES Rescue)',
  'Certificate II in Public Safety (SES)',
  'Certificate III in Public Safety (SES Rescue)',
  'Certificate IV in Training and Assessment',
  'Chainsaw Operator (Cross-Cut & Limb)',
  'Chainsaw Operator (Tree Felling)',
  'Communications Equipment Operator',
  'Community Engagement',
  'Community Liaison Officer',
  'Conduct Briefing and Debriefing',
  'Crash Free Driver',
  'Crew small powercraft in a rescue operation (PUASAR015A)',
  'Drive Operational Vehicles',
  'Emergency Management Arrangements',
  'Emergency Management Overview',
  'Emergency Operations Centre Management',
  'Emergency Response Management',
  'Evacuation Management',
  'Evidence Gatherer',
  'Exercise Management',
  'First Aid - Non-SES',
  'First Aid - SES',
  'Fit for Task (Flood Rescue)',
  'Flood Rescue Awareness',
  'Flood Rescue Boat Operator (FR L2)',
  'Four Wheel Drive Operator',
  'General Rescue',
  'Incident Controller Level 1',
  'Induction / NSW SES Fundamentals',
  'Intro to Community Engagement (Module 1)',
  'Intro to Safe Driving',
  'Introduction to AIIMS',
  'Introduction to AIIMS-4 (eLearning)',
  'Introduction to DOV',
  'Introduction to Emergency Management',
  'Land Search Team Member',
  'Large Animal Rescue',
  'Leading Self Leading Others',
  'Liaise with Local Media',
  'Looking After People',
  'Maintain Team Safety',
  'Maintain safety at an incident scene',
  'Managing an Emergency Operation',
  'Map Reading',
  'Navigate Urban Rural Environments',
  'Participate in a Rescue Operation',
  'Plan & Conduct Public Awareness Program',
  'Planning Engagement (Module 2)',
  'Planning Officer Level 2',
  'RFA Online Advanced User',
  'RFA Online Basic User',
  'RIIWHS202D Enter and Work in Confined Spaces',
  'Rescue From Vehicles in Water',
  'SES Online',
  'Skills Trainer',
  'Skills Trainer and Evidence Gatherer (STEG)',
  'Storm and Water Damage Operation',
  'Swiftwater Rescue Awareness (FR L1)',
  'Swiftwater Rescue Technician (FR L3)',
  'Team Leader',
  'Traffic Controller for Emergency Services',
  'Traffic Safety',
  'Trainer',
  'Trainer - TAE',
  'Trauma Care Workshop',
  'USAR Category 1',
  'Vertical Rescue (PUASAR004B/PUASAR032A)',
  'Vertical Rescue Operator',
  'Waterways Authority License Test',
  'Work in an Emergency Operations Centre',
  'Work in an Operations Centre',
  'Working with the Media'
];

export const FEATURED = [
  'Chainsaw Operator (Cross-Cut & Limb)',
  'Swiftwater Rescue Awareness (FR L1)',
  'Flood Rescue Boat Operator (FR L2)',
  'Swiftwater Rescue Technician (FR L3)',
  'Land Search Team Member',
  'Storm and Water Damage Operation',
  'Vertical Rescue (PUASAR004B/PUASAR032A)',
];

export const ABBREVIATIONS = {
  'Chainsaw Operator (Cross-Cut & Limb)': 'CS',
  'Swiftwater Rescue Awareness (FR L1)': 'L1',
  'Flood Rescue Boat Operator (FR L2)': 'L2',
  'Swiftwater Rescue Technician (FR L3)': 'L3',
  'Land Search Team Member': 'LS',
  'Storm and Water Damage Operation': 'SWD',
  'Vertical Rescue (PUASAR004B/PUASAR032A)': 'VR',
};
